language: php
services:
  - mysql
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm
env:
  # composer install (uses lock file)
  #
  # The lock file is only used by developers of the library and ensures
  # a sane dev environment.
  #
  # Everything below local dev PHP version _or_ platform req expected to fail
  # HHVM expected to fail for some platform reqs
  - DEPS='lock'
  # composer update --prefer-lowest
  #
  # Ensures that the lowest possible versions will work
  #
  # HHVM may fail here if older versions required HHVM specific changes
  # to be compatible
  - DEPS='low'
  # composer update
  #
  # This uses the latest possible dependencies for the given PHP version.
  #
  # If a platform requirement is set, this may not be actual latest versions
  # and they may be incompatible with newer PHP versions if the PHP requirement is
  # lax (e.g. >=5.3.6 and a platform of 5.3.6 running on 7.0 which doesn't include
  # necessary bug fixes for 7.0)
  - DEPS='high'
matrix:
  fast_finish: true
  allow_failures:
    # HHVM may fail in all configurations
    - php: hhvm
    # PHP nightly may fail in all configuration
    - php: nightly
    # PHP < dev version may fail with composer.lock
    # Currently running PHP 7.1
    - php: 5.5
      env: DEPS='lock'
    - php: 5.6
      env: DEPS='lock'
    - php: 7.0
      env: DEPS='lock'
    # Everything except HHVM/nightly should pass with high/low

sudo: false
before_install:
  - composer self-update
install:
  - if [ "$DEPS" == "lock" ]; then travis_retry composer install --no-interaction --prefer-source; fi;
  - if [ "$DEPS" == "dev" ];  then travis_retry composer update --minimum-stability=dev --no-interaction --prefer-source; fi;
  - if [ "$DEPS" == "low" ];  then travis_retry composer update --prefer-lowest --no-interaction --prefer-source; fi;
  - if [ "$DEPS" == "high" ];  then travis_retry composer update --no-interaction --prefer-source; fi;
  - composer show --tree
script: php vendor/bin/phpunit
after_script: if (( `php -r 'echo PHP_MAJOR_VERSION;'` == 7 )); then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/coverage/coverage.clover; fi;
notifications:
  slack:
    secure: iICr/FzdFTh9qq+k3uUHuygnrE7hyJtsHNxkcHQeL1pFucgd5G+nruLqrP3gxBnOAt1hMPZ8kW7N/SK/l09VHDSqiQFEzPlUv/tkFH3cm4TSyVa9Z+2p/OgB5Z2qd1J24X5H+c1tj1fqnKgXuM5WyBVdwR5V2wyquqNlwQx7S+WpwXztoNg2DJghxOq8NOQ50R+2FroZ4YUzkBN3Fq8ksPl3yREY0/wuxUu72O0b+GWiectSVcBjCRchnovy3HssH+fjzHbowCVVKZalzOpD+sx5hYcATDKU5U7qHDKsUlB3mhwkRYeLEmFFPfTmPQ8znn0nSH2zR+DQXuZ7SqDdBFClCQdkaUtTkFzKW146GnryfTDl0eQFmaQPAUVkZTTAL9HPgJszbS50FvDVjsHqpMkhUaB5ZfvlaFobRrdob8HOFTJ9MOD+l0hzX9a/y7uPpeLAqoRH4OiprWPh8AFG069SKaiIzkRDD7l89TA7l3KSeR8rrGGp79tB6PwKjTzBhF9UN7Iw8rDgY6KCEolxFxyaYXi3HaMybKKSt+i86G/ZLFqIvZpp2bgz/D+jY/HuP92PL3rIoBUHDNRLq+YROC0sJ3emPCi2w/BPPZvk1co1g0fIjPrLoNygJr8M6AJjYJo9IcMZTgRSmk8BcyeVPkxLoPmrGIss29CqIb8U7+M=
